# Generated by ./update.sh - do not update manually!
# Last updated: 2026-09-02
# Linux is pinned to 1.7.0 by hand: the update manifests advertise
# 1.7.1, but its AppImages are not served (HTTP 404, 2026-09-02).
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "1.7.1";
    src = fetchurl {
      url = "https://dl.fastmailcdn.com/desktop/production/mac/arm64/Fastmail-1.7.1-arm64-mac.zip";
      hash = "sha512-PFWj+tHSZLCI/GuduHpFci/CTyxr6CT+OQHlVDc7DiI5BKwbNUfm/4IF2iwNfg5d5s5G+e/ZpJNxQUmfj+x26w==";
    };
  };
  aarch64-linux = {
    version = "1.7.0";
    src = fetchurl {
      url = "https://dl.fastmailcdn.com/desktop/production/linux/arm64/com.fastmail.Fastmail-1.7.0-arm64.AppImage";
      hash = "sha512-rs2T2dliVjPgcWxcdqXbGkUlms4xoFdS5GxTriLBPK+52qM/icBvKAkPO97Q/zjWGFSNGQlcRznG5GuT0ja9hA==";
    };
  };
  x86_64-linux = {
    version = "1.7.0";
    src = fetchurl {
      url = "https://dl.fastmailcdn.com/desktop/production/linux/x64/com.fastmail.Fastmail-1.7.0.AppImage";
      hash = "sha512-d2RNpq0idNcVRXiQs4bSOdLry9vPVOKAnOVxeZEBY8ulsDziT1DEOTQz0FmA8JGl7MEws5rb20FBMXYGJw+hsw==";
    };
  };
}
